### PR TITLE
Upgrade/tensorflow

### PR DESCRIPTION
**Pull request by Spiess**
Upgrades the used version of TensorFlow from 0.3.1 to 0.4.1.

## Persistent issues
- The `MovenetMultiposeDetector` causes a NullPointerException at `Skeleton.java:96`, but this issue also occurs on master.

### CODE REVIEW

**Comment by lucaro** [comment]
`Skeleton.java:96` is just a data access. Could you elaborate on that NPE?

**Comment by Spiess** [comment]
The full stack trace (reproducible using [this test image](http://www.trbimg.com/img-590c9115/turbine/ct-15-yoga-poses-to-heal-your-whole-body-20170505)) is:
```
java.lang.NullPointerException                                                                                                                                                                                                                      
        at org.vitrivr.cineast.core.data.Skeleton.getPoint(Skeleton.java:96)                                                                                                                                                                        
        at org.vitrivr.cineast.core.features.SkeletonPose.angle(SkeletonPose.java:354)                                                                                                                                                              
        at org.vitrivr.cineast.core.features.SkeletonPose.getAnglesAndWeights(SkeletonPose.java:221)                                                                                                                                                
        at org.vitrivr.cineast.core.features.SkeletonPose.persist(SkeletonPose.java:88)                                                                                                                                                             
        at org.vitrivr.cineast.core.features.SkeletonPose.processSegment(SkeletonPose.java:107)                                                                                                                                                     
        at org.vitrivr.cineast.standalone.runtime.ExtractionTask.run(ExtractionTask.java:28)                                                                                                                                                        
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                                                                
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                                                                
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lucaro** [comment]
Great, thanks, I'll have a look

**Comment by Spiess** [comment]
I have opened a new issue (#295) to move this discussion away from this pull request since I also encountered this problem on master.

For some reason the stack trace is slightly more verbose when using the GPU version of TensorFlow.

**Review by lucaro — APPROVED** [review]
Looks all quite reasonable to me.

**Pull request merged**
